# Jekyll configuration
# Use _config.build.yml to override these settings on `grunt build`.

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

title: 'Development, sports, and more by @PacoGuzman'
url: 'http://localhost:3000'
author: 'Paco Guzmán'
twitter: 'pacoguzman'
email: 'pacoguzmanp@gmail.com'
description: 'Paco Guzmán is a Back End Developer from Madrid, Spain'

environment: development

exclude: ['css', 'img', 'js', 'fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.svg', '**.ico']
keep_files: ['perf']

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

category_title_prefix: ''
category_dir: /

permalink: /:year/:month/:title/
paginate: 5

# disable this with ''
excerpt_separator: ''

# Use Pygments to highlight code blocks
highlighter: pygments
