gems: [bourbon, neat]

# Structure configuration
source: source
destination: _site

assets:
  cachebust: soft

# Global settings
timezone: Madrid
encoding: utf-8

# Site settings
title: Riding to NoWhere
email: pacoguzmanp@gmail.com
description: "Personal blog about Ruby and Rails development and live experiences"
baseurl: ""
url: "https://pacoguzman.github.io"
twitter_username: pacoguzman
github_username:  pacoguzman

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM
