# Global settings
timezone: Madrid
encoding: utf-8

# Site settings
title: Riding to NoWhere
email: pacoguzmanp@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "https://pacoguzman.github.io"
twitter_username: pacoguzman
github_username:  pacoguzman

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM

